### ISSUE TITLE
How do I transfer tokens to an ERC1363 contract?

### ISSUE THREAD

**Issue by CalamariAce** [vittominacori/erc1363-payable-token#21]
I'm trying to transfer tokens to my ERC1363 contract using Remix v0.41. I haven't done this before and may be missing something basic.

This is my contract code:

```
pragma solidity ^0.8.20;

import "erc-payable-token/contracts/token/ERC1363/ERC1363.sol";

contract MyToken is ERC1363 {
    constructor(string memory name, string memory symbol) ERC20(name, symbol) {
        // your stuff
    }

  // your stuff
}
```
I compiled this and successfully deployed the contract to a Remix VM (Shanghai). I want to test transferring some Wei to the contract, so I called the `approveAndCall` function in Remix, using a value of `1` Wei and the `spender` address set to my Remix virtual wallet (same one used to deploy the contract).

However, this transaction fails with the following error message, and I am not sure why. Is this the proper way for me to send tokens to my contract? Any insight is appreciated. Thanks.

![2024-01-18-152050_1920x1056_scrot](https://github.com/vittominacori/erc1363-payable-token/assets/6564637/99304ce6-c8a0-498e-9493-69849b2a9824)

**Comment by vittominacori** [comment]
As defined [here](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/IERC1363Errors.sol#L17), the `ERC1363EOASpender` error indicates a failure with the token `spender` as it can't be an EOA.

You are trying to approve a EOA but it is not possible because that address doesn't implement the required `IERC1363Spender:onApprovalReceived`.

If you want to approve your deployer wallet you can use the standard `ERC20:approve` behavior.

To use the `*AndCall` methods, receivers or spenders MUST implement the required interfaces. In other words they must be smart contracts implementing the required interfaces and returning the required values.

Check the [ERC1363 website](https://erc1363.org/) for more details.
